// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package dz.hanouti.Model;




/************************************************************/

import java.util.Date;

/**
 * 
 */
public class catalogue {
	/**
	 *
	 */
	private Date lastModifDate;
	/**
	 *
	 */
	public product[] product;

	/**
	 *
	 */
	public void search() {
	}

	/**
	 *
	 */
	public void editDate() {
	}

}