// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package dz.hanouti.Model;




/************************************************************/
/**
 * 
 */
public class LineSale {
				/**
				 * 
				 */
				private String barCode;
				/**
				 * 
				 */
				private float subTotal;
				/**
				 * 
				 */
				private int quantity;
				/**
				 * 
				 */
				private float unitPrice;
	/**
	 * 
	 */
	public void addLine() {
	}
	/**
	 * 
	 */
	public void editLine() {
	}
	/**
	 * 
	 */
	public void deleteLine() {
	}
	/**
	 * 
	 */
	public void calculateSubTotal() {
	}
}
