// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package dz.hanouti.Model;

/************************************************************/
/**
 * 
 */
public class product {
				/**
				 * 
				 */
				private int barCode;
				/**
				 * 
				 */
				private float buyPrice;
				/**
				 * 
				 */
				private String location;
				/**
				 * 
				 */
				private int quantity;
				/**
				 * 
				 */
				private String position;
				/**
				 * 
				 */
				private float sellPrice;
				/**
				 * 
				 */
				private String typeProd;
	/**
	 * 
	 */
	public void addProduct() {
	}
	/**
	 * 
	 */
	public void editProduct() {
	}
	/**
	 * 
	 */
	public void deleteProduct() {
	}
	/**
	 * 
	 */
	public void supply() {
	}
}
