// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package dz.hanouti.Model;





/************************************************************/

import java.util.Date;

/**
 * 
 */
public class Sale {
				/**
				 * 
				 */
				private String idSale;
				/**
				 * 
				 */
				private Date date;
				/**
				 * 
				 */
				private float total;
				/**
				 * 
				 */
				public LineSale[] LineSale;
	/**
	 * 
	 */
	public void calculateTotal() {
	}
	/**
	 * 
	 */
	public void addSale() {
	}
	/**
	 * 
	 */
	public void deleteSale() {
	}
	/**
	 * 
	 */
	public void editSale() {
	}
	/**
	 * 
	 */
	public void validateSale() {
	}
}
